### ISSUE TITLE
implement name query param in /products

### ISSUE THREAD

**Issue by ak-seyam** [Delta-Shop/end-point#2]
PS: it is related to #1 I was thinking about closing this issue and make a comment on the first one I'm not so sure, anyway I will keep it open for you to see it 🤷‍♂️
# Motivation:
We currently had some filtering criteria, if we added an optional name param we can use it for search without implementing a new feature.
# My Suggestion:
Just add a `?search_term` or `?name` to the current items I will use "name" temporarily until we settle on an option.

**Comment by abdo1819** [comment]
ok, will follow up here.

I was suggesting `?q`  because it is the default query parameter for search and makes the browser search by clicking the tab https://opensource.zalando.com/restful-api-guidelines/#q

**Comment by abdo1819** [comment]
here for now 
https://github.com/Delta-Shop/end-point/commit/0b19e3d5a751237be87227b380425ccf10fae113

**Comment by abdo1819** [comment]
closed for no response
