### ISSUE TITLE
after and before for cursor based pagination are not clear

### ISSUE THREAD

**Issue by ak-seyam** [Delta-Shop/end-point#3]
in the doc, it says they will take a string without specifying what kind of string it should have, id? product name?

**Comment by abdo1819** [comment]
external resource [v2.4#paging](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.4#paging)

# front-client 
from a front-end perspective, you don't need to know what is it you will initiate a request without it and get the next page `after` and `before` in response
> note this will make it impossible to make offset pagination as you only know the before and after

# backend-server
here you make it whatever you want as long as it is unique to the entity but suggest not using the database id we may use cyphered `id` that is easy to inverse

**Comment by abdo1819** [comment]
for we only use `cursor` paging everywhere  we may add offset paging per request as I think we may need it for `products`

**Comment by abdo1819** [comment]
inactive open again if want talk
